version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  bot:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/bot-fire-water-sources:latest
    env_file: .env
    command: python main.py
    depends_on:
      - redis

  worker:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/bot-fire-water-sources:latest
    env_file: .env
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis

volumes:
  redis_data:
